version: '3.8'
services:
  market-web-dev:
    image: mhmarket/web:latest
    container_name: market-web
    environment:
      PORT: 9500
      API_URL: http://103.162.20.141:8000/api/v2
    ports:
      - "9500"
    networks:
      - mh-network
    dns:
      - 192.168.200.4
      - 8.8.8.8
networks:
  mh-network:
    driver: bridge