version: '3.8'
services:
  market-web-dev:
    image: mhmarket/web:latest
    container_name: market-web
    environment:
      VITE_BASE_URL: http://103.162.20.141:8000/api/v2
    ports:
      - "9500:3000"
    networks:
      - mh-network
    dns:
      - 192.168.200.4
      - 8.8.8.8
    volumes:
      - ./:/app/

networks:
  mh-network:
    driver: bridge

    version: "3.7"
      services:
      frontend:
        build:
        context: .
        container_name: frontend
        ports:
          - "3000:80" # map 80 in container => 3000 in local

